name: CI/CD

on:
  push:
    branches:
      - $default-branch

jobs:
  ci-cd:
    name: Build and deploy
    uses: health-education-england/.github/.github/workflows/ci-cd-gradle.yml@main
    # TODO: add cluster-prefix
    # with:
    #   cluster-prefix:
    secrets:
      codeartifact-username: ${{ secrets.AWS_MAVEN_USERNAME }}
      codeartifact-password: ${{ secrets.AWS_MAVEN_PASSWORD }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
