name: CI/CD

on:
  push:
    branches:
      - $default-branch

jobs:
  ci-cd:
    name: Build and deploy
    uses: health-education-england/.github/.github/workflows/ci-cd-gradle.yml@main
    with:
      use-codeartifact: false
      # TODO: add cluster-prefix
      # cluster-prefix:
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
