name: PR Analysis

on:
  pull_request:
    branches:
      - $default-branch

jobs:
  analysis:
    name: Analyse PR
    uses: health-education-england/.github/.github/workflows/pr-analysis-maven.yml@main
    with:
      use-codeartifact: false
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
