name: Build

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      use-codeartifact:
        description: Whether code artifact should be used to perform the build.
        required: false
        type: boolean
      java-version:
        default: "17"
        description: The Java version used in the workflow.
        type: string
    secrets:
      checkout-token:
        description: The token used for performing checkout.
        required: false
      sonar-token:
        description: A token allowing access to SonarCloud.
        required: true

jobs:
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.6

  build:
    name: Build
    needs: validate-wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for determining submodules
        uses: actions/checkout@v4

      - name: Determine Submodules
        id: check-submodules
        run: |
          if [ -f .gitmodules ]; then
            echo "submodule_checkout_strategy=recursive" >> $GITHUB_OUTPUT
          else
            echo "submodule_checkout_strategy=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: ${{ steps.check-submodules.outputs.submodule_checkout_strategy }}
          token: ${{ secrets.checkout-token ||  github.token }}

      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Configure AWS credentials
        if: inputs.use-codeartifact
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::430723991443:role/github-actions-deployer-role

      - name: Add CodeArtifact env var
        if: inputs.use-codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain hee --domain-owner 430723991443 --query authorizationToken --output text --duration-seconds 900`
          echo CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN >> $GITHUB_ENV
          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"

      - name: Build
        run: ./gradlew build

      - name: Analyse quality
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: ./gradlew sonarqube

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::430723991443:role/github-actions-deployer-role

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
        run: |
          ./gradlew bootBuildImage --imageName=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
