name: CI/CD

on:
  workflow_call:
    inputs:
      cluster-prefix:
        description: The prefix of the ECS cluster to target for deployment.
        required: true
        type: string
      service-name:
        description: The name of the service being deployed, defaults to repository name.
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      use-codeartifact:
        description: Whether code artifact should be used to perform the build.
        required: false
        type: boolean
    secrets:
      sonar-token:
        description: A token allowing access to SonarCloud.
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-gradle.yml
    with:
      use-codeartifact: ${{ inputs.use-codeartifact }}
    secrets:
      sonar-token: ${{ secrets.sonar-token }}

  deploy-preprod:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: preprod
      service-name: ${{ inputs.service-name}}

  clear-outdated-runs:
    needs: deploy-preprod
    uses: ./.github/workflows/clear-runs.yml
    secrets:
      github-token: ${{ secrets.MACHINE_TOKEN }}

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: prod
      service-name: ${{ inputs.service-name}}
