name: CI/CD

on:
  workflow_call:
    inputs:
      cluster-prefix:
        description: The prefix of the ECS cluster to target for deployment.
        required: true
        type: string
      service-name:
        description: The name of the service being deployed, defaults to repository name.
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      use-codeartifact:
        description: Whether code artifact should be used to perform the build.
        required: false
        type: boolean
    secrets:
      codeartifact-username:
        description: The username to access the codeartifact repository.
        required: false
      codeartifact-password:
        description: The password to access the codeartifact repository.
        required: false
      ecr-username:
        description: The username to access the elastic container registry.
        required: false
      ecr-password:
        description: The username to access the elastic container registry.
        required: false
      sonar-token:
        description: A token allowing access to SonarCloud.
        required: true

jobs :
  build:
    uses: ./.github/workflows/build-gradle.yml
    with:
      use-codeartifact: ${{ inputs.use-codeartifact }}
    secrets:
      sonar-token: ${{ secrets.sonar-token }}


  deploy-preprod:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: preprod
      service-name: ${{ inputs.service-name}}

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: prod
      service-name: ${{ inputs.service-name}}
