name: CI/CD

on:
  workflow_call:
    inputs:
      cluster-prefix:
        description: The prefix of the ECS cluster to target for deployment.
        required: true
        type: string
      service-name:
        description: The name of the service being deployed, defaults to repository name.
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      use-codeartifact:
        description: Whether code artifact should be used to perform the build.
        required: false
        type: boolean
      java-version:
        default: "17"
        description: The Java version used to build the project
        type: string
    secrets:
      sonar-token:
        description: A token allowing access to SonarCloud.
        required: true
      reject-pat:
        description: The Personal Access Token (PAT) used for rejecting runs.
        required: false

jobs:
  build:
    uses: ./.github/workflows/build-gradle.yml
    with:
      use-codeartifact: ${{ inputs.use-codeartifact }}
      java-version: ${{ inputs.java-version }}
    secrets:
      sonar-token: ${{ secrets.sonar-token }}

  deploy-preprod:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: preprod
      service-name: ${{ inputs.service-name}}

  clear-outdated-runs:
    needs: deploy-preprod
    uses: ./.github/workflows/clear-runs.yml
    with:
      environment: prod
    secrets:
      reject-pat: ${{ secrets.reject-pat }}

  deploy-prod:
    needs: deploy-preprod
    uses: ./.github/workflows/deploy.yml
    with:
      cluster-prefix: ${{ inputs.cluster-prefix }}
      environment: prod
      service-name: ${{ inputs.service-name}}
