name: PR Analysis

permissions:
  id-token: write
  pull-requests: write
  contents: read

on:
  workflow_call:
    inputs:
      use-codeartifact:
        description: Whether code artifact should be used to perform the build.
        required: false
        type: boolean
      java-version:
        default: "17"
        description: The Java version used in the workflow.
        type: string
    secrets:
      checkout-token:
        description: The token used for performing checkout.
        required: false
      sonar-token:
        description: A token allowing access to SonarCloud.
        required: true

jobs:
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v2.1.1

  analyse:
    name: Analyse PR
    needs: validate-wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for determining submodules
        uses: actions/checkout@v4

      - name: Determine Submodules
        id: check-submodules
        run: |
          if [ -f .gitmodules ]; then
            echo "submodule_checkout_strategy=recursive" >> $GITHUB_OUTPUT
          else
            echo "submodule_checkout_strategy=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          remote: true
          submodules: ${{ steps.check-submodules.outputs.submodule_checkout_strategy }}
          token: ${{ secrets.checkout-token ||  github.token  }}

      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          cache: gradle
          distribution: temurin
          java-version: ${{ inputs.java-version }}

      - name: Configure AWS credentials
        if: inputs.use-codeartifact
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::430723991443:role/github-actions-deployer-role

      - name: Add CodeArtifact env var
        if: inputs.use-codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain hee --domain-owner 430723991443 --query authorizationToken --output text --duration-seconds 900`
          echo CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN >> $GITHUB_ENV
          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"

      - name: Build
        run: ./gradlew build

      - name: Get modified files
        id: changed-files
        uses: Ana06/get-changed-files@v2.2.0

      - name: Check modified files
        id: check-files
        run: |
          do_analysis=false
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ $changed_file =~ ^(.*\/|)src\/.+$ ]]; then
              do_analysis=true
              break
            fi
          done
          echo "do-analysis=$do_analysis" >> $GITHUB_OUTPUT

      - name: Notify skipped analysis
        if: steps.check-files.outputs.do-analysis == 'false'
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          repo-token: ${{ github.token }}
          message: |
            Quality analysis was skipped as no source changes were detected.

      - name: Analyse quality
        if: steps.check-files.outputs.do-analysis == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: ./gradlew sonarqube
