name: PR Analysis - Common

permissions:
  pull-requests: read

on:
  workflow_call:

jobs:
  analyse:
    name: Analyse PR
    runs-on: ubuntu-latest

    steps:
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6.2.1
