name: PR Analysis - Common

permissions:
  contents: read

on:
  workflow_call:

jobs:
  analyse:
    name: Analyse PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5.4.4
